name: catalog-build-deploy

on:
    workflow_dispatch:
        inputs:
            environment:
                description: The targeted environment to deploy to (all lower environments will also be deployed to)
                type: choice
                required: true
                options:
                    - dev
                    - ppd
    
permissions:
    id-token: write
    contents: read

jobs:
    deploy-dev:
        runs-on: ubuntu-latest
        environment: 
            name: dev
        steps:
            - name: Az CLI login via OIDC
              uses: azure/login@v1
              with:
    
                client-id: ${{secrets.AZURE_CLIENT_ID}}
                tenant-id: ${{secrets.AZURE_TENANT_ID}}
                subscription-id: ${{secrets.AZURE_SUBSCRIPTION_ID}}

            - name: Run Az commands
              run: |
                az account show
                az group list

    deploy-ppd:
        runs-on: ubuntu-latest
        environment: 
            name: ppd
        needs:
            - deploy-dev
        if: |
            github.event.inputs.environment =='ppd'
        steps:
            - name: Az CLI login via OIDC
              uses: azure/login@v1
              with:
    
                client-id: ${{secrets.AZURE_CLIENT_ID}}
                tenant-id: ${{secrets.AZURE_TENANT_ID}}
                subscription-id: ${{secrets.AZURE_SUBSCRIPTION_ID}}

            - name: Run Az commands
              run: |
                az account show
                az group list