name: catalog-build-deploy

on:
    workflow_dispatch:
        inputs:
            environment:
                description: The targeted environment to deploy to (all lower environments will also be deployed to)
                type: choice
                required: true
                options:
                    - dev
                    - ppd
    
permissions:
    id-token: write
    contents: read

env:
    DOTNET_VERISON: 8.0.x    

jobs:
    build:
     runs-on: ubuntu-latest
     steps:
        # Checkout the repo
        - uses: actions/checkout@v4
        
        # Setup .NET Sdk
        - name: Set up .NET
          uses: actions/setup-dotnet@v4
          with: 
            dotnet-verison: ${{env.DOTNET_VERISON}}
        
        # Explore Directory Structure
        - name: Display Directory Structure
          run: ls -R

        # Restore Dependencies
        # - name: Install Dependencies
        #   run: dotnet restore ./
    
    deploy-dev:
        runs-on: ubuntu-latest
        environment: 
            name: dev
        steps:
            - name: Az CLI login via OIDC
              uses: azure/login@v1
              with:
    
                client-id: ${{secrets.AZURE_CLIENT_ID}}
                tenant-id: ${{secrets.AZURE_TENANT_ID}}
                subscription-id: ${{secrets.AZURE_SUBSCRIPTION_ID}}

            - name: Run Az commands
              run: |
                az account show
                az group list

    deploy-ppd:
        runs-on: ubuntu-latest
        environment: 
            name: ppd
        needs:
            - deploy-dev
        if: |
            github.event.inputs.environment =='ppd'
        steps:
            - name: Az CLI login via OIDC
              uses: azure/login@v1
              with:
    
                client-id: ${{secrets.AZURE_CLIENT_ID}}
                tenant-id: ${{secrets.AZURE_TENANT_ID}}
                subscription-id: ${{secrets.AZURE_SUBSCRIPTION_ID}}

            - name: Run Az commands
              run: |
                az account show
                az group list