name: catalog-build-deploy

on:
    workflow_dispatch:
        inputs:
            environment:
                description: The targeted environment to deploy to (all lower environments will also be deployed to)
                type: choice
                required: true
                options:
                    - dev
                    - ppd
                    - prod  
    
permissions:
    id-token: write
    contents: read

env:
    DOTNET_VERISON: 8.0.x    

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            # Checkout the repo
            - uses: actions/checkout@v4
        
            # Setup .NET Sdk
            - name: Set up .NET
              uses: actions/setup-dotnet@v4
              with: 
                dotnet-verison: ${{env.DOTNET_VERISON}}
        
            # Restore Dependencies
            - name: Install Dependencies
              run: dotnet restore ./catalog/src/Eshop.Catalog.Api/Eshop.Catalog.Api.csproj

            # Run dotnet build
            - name: Build with dotnet
              run: dotnet build ./catalog/src/Eshop.Catalog.Api/Eshop.Catalog.Api.csproj --configuration Release --no-restore

            # Run dotnet publish
            - name: Publish
              run: |
                dotnet publish ./catalog/src/Eshop.Catalog.Api/Eshop.Catalog.Api.csproj --configuration Release --no-build --output 'catalog/publish'

            # Upload Artifact
            - name: Upload artifacts for deployment job
              uses: actions/upload-artifact@v4
              with:
                name: 'catalog-artifact'
                path: 'catalog/publish'
                if-no-files-found: error

    deploy-dev:
        runs-on: ubuntu-latest
        environment: 
            name: dev
        needs: [build]
        steps:
            # Checkout the repo
            - uses: actions/checkout@v4
    
            # Download the artifact    
            - name: Download artifact from build job
              uses: actions/download-artifact@v4
              with:
                name: 'catalog-artifact'
                path: 'catalog/publish'

            # Explore Directory Structure
            - name: Display Directory Structure
              run: ls -R
              
            - name: Az CLI login via OIDC
              uses: azure/login@v1
              with:
                client-id: ${{secrets.AZURE_CLIENT_ID}}
                tenant-id: ${{secrets.AZURE_TENANT_ID}}
                subscription-id: ${{secrets.AZURE_SUBSCRIPTION_ID}}

            - name: Run Az commands
              run: |
                az account show
                az group list

            - name: Deploy to Azure Web App
              uses: azure/webapps-deploy@v3
              with:
                app-name: eshop-catalog-dev
                package: 'catalog/publish'

            - name: Logout from Azure
              run: az logout

    deploy-ppd:
        runs-on: ubuntu-latest
        environment: 
            name: ppd
        needs:
            - deploy-dev
        if: |
            github.event.inputs.environment =='ppd'
        steps:
            # Checkout the repo
            - uses: actions/checkout@v4
    
            # Download the artifact    
            - name: Download artifact from build job
              uses: actions/download-artifact@v4
              with:
                name: 'catalog-artifact'
                path: 'catalog/publish'

            # Explore Directory Structure
            - name: Display Directory Structure
              run: ls -R
              
            - name: Az CLI login via OIDC
              uses: azure/login@v1
              with:
    
                client-id: ${{secrets.AZURE_CLIENT_ID}}
                tenant-id: ${{secrets.AZURE_TENANT_ID}}
                subscription-id: ${{secrets.AZURE_SUBSCRIPTION_ID}}

            - name: Run Az commands
              run: |
                az account show
                az group list
            
            - name: Deploy to Azure Web App
              uses: azure/webapps-deploy@v3
              with:
                app-name: eshop-catalog-ppd
                package: 'catalog/publish'

            - name: Logout from Azure
              run: az logout
    
    deploy-prod:
        runs-on: ubuntu-latest
        environment: 
            name: prod
        needs:
            - deploy-ppd
        if: |
            github.event.inputs.environment =='prod' || needs.deploy-ppd.result == 'success'
        steps:
            # Checkout the repo
            - uses: actions/checkout@v4
    
            # Download the artifact    
            - name: Download artifact from build job
              uses: actions/download-artifact@v4
              with:
                name: 'catalog-artifact'
                path: 'catalog/publish'

            # Explore Directory Structure
            - name: Display Directory Structure
              run: ls -R
              
            - name: Az CLI login via OIDC
              uses: azure/login@v1
              with:
    
                client-id: ${{secrets.AZURE_CLIENT_ID}}
                tenant-id: ${{secrets.AZURE_TENANT_ID}}
                subscription-id: ${{secrets.AZURE_SUBSCRIPTION_ID}}

            - name: Run Az commands
              run: |
                az account show
                az group list
            
            - name: Deploy to Azure Web App
              uses: azure/webapps-deploy@v3
              with:
                app-name: eshop-catalog-prod
                package: 'catalog/publish'

            - name: Logout from Azure
              run: az logout